/* eslint-disable */
/* global WebImporter */

// PAGE TEMPLATE CONFIGURATION
const PAGE_TEMPLATE = {
  name: 'news',
  description: 'News/advocacy article page with default content only (title, hero image, article body, metadata). Sidebar, related topics, and disclaimer are auto-generated by template.',
  urls: [
    'https://www.racq.com.au/news/advocacy/easter-crash-analysis-shows-trauma-is-often-closer-to-home',
  ],
  blocks: [],
  metadata: {
    template: 'news',
  },
};

/**
 * Extract article-specific metadata from the page DOM
 */
function extractArticleMetadata(document) {
  const meta = {};

  // Author
  const author = document.querySelector('.article-detail__author');
  if (author) {
    meta.author = author.textContent.trim();
  }

  // Publish date
  const date = document.querySelector('.article-detail__date');
  if (date) {
    meta.publishDate = date.textContent.trim();
  }

  // Category
  const category = document.querySelector('.article-detail__category .field-value');
  if (category) {
    meta.category = category.textContent.trim();
  }

  // Tags from tag-list
  const tagLinks = document.querySelectorAll('.tag-list .tag-links');
  if (tagLinks.length > 0) {
    meta.tags = [...tagLinks].map((t) => t.textContent.trim()).join(', ');
  }

  // Template
  meta.template = PAGE_TEMPLATE.metadata.template;

  return meta;
}

/**
 * Build the article content from the source DOM
 */
function buildArticleContent(document, main) {
  const article = document.createElement('div');

  // 1. H1 title
  const title = main.querySelector('.article-detail__title');
  if (title) {
    article.append(title);
  }

  // 2. Hero image
  const heroImg = main.querySelector('.article-detail__image img');
  if (heroImg) {
    const p = document.createElement('p');
    p.append(heroImg);
    article.append(p);
  }

  // 3. Article body - intro paragraph
  const introContent = main.querySelector('.article-detail__content');
  if (introContent) {
    [...introContent.children].forEach((child) => article.append(child));
  }

  // 4. Article body - main rich text
  const richTextSections = main.querySelectorAll('.article-detail__placeholder .rich-text .component-content');
  richTextSections.forEach((section) => {
    [...section.children].forEach((child) => article.append(child));
  });

  return article;
}

export default {
  transform: ({ document, url, html, params }) => {
    const main = document.body;

    // Extract article metadata before DOM manipulation
    const articleMeta = extractArticleMetadata(document);

    // Build clean article content
    const article = buildArticleContent(document, main);

    // Clear main and replace with article content
    main.innerHTML = '';
    main.append(article);

    // Apply WebImporter built-in rules
    WebImporter.rules.transformBackgroundImages(main, document);
    WebImporter.rules.adjustImageUrls(main, url, params.originalURL);

    // Create metadata block with standard + custom fields
    const meta = {};

    const title = document.querySelector('title');
    if (title) {
      meta.Title = title.textContent.replace(/[\n\t]/gm, '').trim();
    }

    const desc = document.querySelector('[property="og:description"]');
    if (desc) {
      meta.Description = desc.content;
    }

    const ogImg = document.querySelector('[property="og:image"]');
    if (ogImg) {
      const el = document.createElement('img');
      el.src = ogImg.content;
      meta.Image = el;
    }

    // Add article-specific metadata
    if (articleMeta.author) meta.author = articleMeta.author;
    if (articleMeta.publishDate) meta.publishDate = articleMeta.publishDate;
    if (articleMeta.category) meta.category = articleMeta.category;
    if (articleMeta.tags) meta.tags = articleMeta.tags;
    if (articleMeta.template) meta.template = articleMeta.template;

    const metadataBlock = WebImporter.Blocks.getMetadataBlock(document, meta);
    main.append(document.createElement('hr'));
    main.append(metadataBlock);

    // Generate sanitized path
    const path = WebImporter.FileUtils.sanitizePath(
      new URL(params.originalURL).pathname.replace(/\/$/, '').replace(/\.html$/, ''),
    );

    return [{
      element: main,
      path,
      report: {
        title: document.title,
        template: PAGE_TEMPLATE.name,
        author: articleMeta.author || '',
        publishDate: articleMeta.publishDate || '',
        category: articleMeta.category || '',
      },
    }];
  },
};
