/* eslint-disable */
/* global WebImporter */

// TRANSFORMER IMPORTS
import racqCleanupTransformer from './transformers/racq-cleanup.js';

// TRANSFORMER REGISTRY
const transformers = [
  racqCleanupTransformer,
];

// PAGE TEMPLATE CONFIGURATION - Embedded from page-templates.json
const PAGE_TEMPLATE = {
  name: 'news',
  description: 'News/advocacy article page with default content only (title, hero image, article body, metadata). Sidebar, related topics, and disclaimer are auto-generated by template.',
  urls: [
    'https://www.racq.com.au/news/advocacy/easter-crash-analysis-shows-trauma-is-often-closer-to-home',
    'https://www.racq.com.au/news/racq-in-the-community/racq-helps-supercharge-energy-resilience-in-qld-communities',
  ],
  blocks: [],
  sections: [
    {
      id: 'section-1',
      name: 'Article Content',
      selector: 'div.component.content.article-detail',
      style: null,
      blocks: [],
      defaultContent: [
        'h1.article-detail__title',
        'div.article-detail__content',
        'div.article-detail__image',
        'div.article-detail__placeholder div.component.rich-text',
      ],
    },
  ],
};

/**
 * Execute all page transformers for a specific hook
 * @param {string} hookName - 'beforeTransform' or 'afterTransform'
 * @param {Element} element - The DOM element to transform
 * @param {Object} payload - { document, url, html, params }
 */
function executeTransformers(hookName, element, payload) {
  const enhancedPayload = {
    ...payload,
    template: PAGE_TEMPLATE,
  };

  transformers.forEach((transformerFn) => {
    try {
      transformerFn.call(null, hookName, element, enhancedPayload);
    } catch (e) {
      console.error(`Transformer failed at ${hookName}:`, e);
    }
  });
}

// EXPORT DEFAULT CONFIGURATION
export default {
  transform: (payload) => {
    const { document, url, params } = payload;

    const main = document.body;

    // 1. Execute beforeTransform transformers (initial cleanup)
    executeTransformers('beforeTransform', main, payload);

    // 2. Extract report fields before cleanup removes them
    const authorEl = main.querySelector('.article-detail__author');
    const dateEl = main.querySelector('.article-detail__date');
    const categoryEl = main.querySelector('.article-detail__category .field-value, .article-detail__category');
    const author = authorEl ? authorEl.textContent.trim() : '';
    const publishedDate = dateEl ? dateEl.textContent.trim() : '';
    const category = categoryEl ? categoryEl.textContent.trim() : '';

    // 3. No blocks to parse - this template uses only default content

    // 4. Execute afterTransform transformers (remove non-authorable content)
    executeTransformers('afterTransform', main, payload);

    // 5. Apply WebImporter built-in rules
    const hr = document.createElement('hr');
    main.appendChild(hr);
    WebImporter.rules.createMetadata(main, document);
    WebImporter.rules.transformBackgroundImages(main, document);
    WebImporter.rules.adjustImageUrls(main, url, params.originalURL);

    // 6. Generate sanitized path
    const path = WebImporter.FileUtils.sanitizePath(
      new URL(params.originalURL).pathname.replace(/\/$/, '').replace(/\.html$/, ''),
    );

    return [{
      element: main,
      path,
      report: {
        title: document.title,
        template: PAGE_TEMPLATE.name,
        author,
        publishedDate,
        category,
        blocks: [],
      },
    }];
  },
};
